### ISSUE TITLE
Understanding the RF Image example

### ISSUE THREAD

**Issue by zhengzangw** [yizhou-wang/cruw-devkit#4]
In the tutorial, I have three questions about the first example (In [11], RGB Image with seq_name `2019_04_09_BMS1000`, with only a bicycle).

- In the RGB image, the cyclist seems small in horizontal, while it seems very 'wide' in RF Image. Is there due to the not uniformed angle axis, or are there other possible causes? 
- In ROD2021, it says the radar has FOV ±60°, but the RF image, which ranges from -90° to +90°, has Radar data also in column 0. As I understood, Radar information should only appear on the x-axis from 9 to 118, corresponding to the ±60°.
- In the RF Image, apart from the cyclist, many small horizontal lines have no corresponding objects in the RGB Image. Should we interpret them as noise signal?

Thanks for your attention. I’m looking forward to your reply.

**Comment by yizhou-wang** [comment]
- The reflection pattern is "wide" because the angle resolution of the radar is significantly lower than the range resolution. 
- The radar has the capability of -90 to +90°. However, the performance is very poor when the angle is near ±90°. Thus, in ROD2021, we only evaluate within ±60°.
- Yes, there may be heavy noises existing in some RF images, which is also a challenge for radar object detection.

**Comment by zhengzangw** [comment]
Thanks a lot!
